filter:
    paths: ["src/*"]
tools:
    external_code_coverage: true
    php_code_coverage: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
    php_loc: true

