sudo: required
dist: trusty
services:
  - mongodb
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
before_install:
  - composer self-update
install:
  - composer update --ignore-platform-reqs --prefer-source
before_script:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then phpenv config-add travis-php.ini; fi
  - if [[ $TRAVIS_PHP_VERSION = "hhvm" ]]; then sudo cat travis-php.ini >> /etc/hhvm/php.ini; ./build-mongodb.sh; fi
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
cache:
  directories:
    - $HOME/.composer/cache
