sudo: required
dist: trusty
services:
  - mongodb
language: php
php:
  - 7.0
  - 7.1
  - 7.2
before_install:
  - composer self-update
install:
  - composer update --ignore-platform-reqs --prefer-source
before_script:
  - phpenv config-add travis-php.ini
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
cache:
  directories:
    - $HOME/.composer/cache
